### ISSUE TITLE
Getting pen to drop effectively

### ISSUE THREAD

**Issue by ajfisher** [bjpirt/mirobot-chassis#3]
I've got my bot all working okay except for one thing which is the pen dropping back down into place. It feels like the pen arm is maybe a bit too fitted to the site pieces that it sits within. 

What's the general view of getting it to drop down when the servo moves to the down position?

**Comment by fly72t** [comment]
Same for me. The servo was able to push the pen up but it sticks there. I disassembled half of the robot and tweaked the arm as well as the chassis. It's better but not perfect. Maybe some more exercise will help. My son is practicing geometrical figure and letters.... 
@Ben, with the robots that I had it was always the right side (servo side). A bid wider slot would seriously help.

**Comment by ajfisher** [comment]
Yeah - I had a play with sanding it back over the weekend - looks like mine
is sticking on not just the sides but the bottom point too so I need to
pull it apart and try again. I'd reckon making the slots for it like 1mm
wider in each case would sort it out...

**Comment by bjpirt** [comment]
I've noted this for the next version so am closing this now.
